### ISSUE TITLE
[Feature] Adding `HYBRID` and `NONLOCAL` input parameters

### ISSUE THREAD

**Issue by ezpzbz** [chrisjsewell/aiida-crystal17#37]
Hi @chrisjsewell,
Along writing a workchain, we need to play around with the amount of exact Hartree-Fock exchange. To my knowledge reading related part of the code, plugin currently does not support these two keywords.
I would be happy to make a PR and add them. I thought to open an issue for possible discussion before taking any further action. 
Cheers,
Pezhman

**Comment by chrisjsewell** [comment]
Heya, my quick response would be yes PRs are certainly welcome 👍

**Comment by ezpzbz** [comment]
It was really quick response 😉 
I'll do it then. That would be probably continued with adding another properties calculation. 

On sort of related note - can we pass user-defined retrieved list such as `addition_retrieve_list`?

**Comment by chrisjsewell** [comment]
> That would be probably continued with adding another properties calculation.

sounds good 😄 

> On sort of related note - can we pass user-defined retrieved list such as addition_retrieve_list?

hmm, not sure off-hand, that will be a more delayed response lol

**Comment by ezpzbz** [comment]
Thanks a bunch. Cheers.
